task_lad/task_lad/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('task_page.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

task_lad/task_page/urls.py
from django.urls import path
from . import views

app_name = 'task_page'

urlpatterns = [
    path("", views.index, name='index'),
    path("login/", views.login_user, name="login"),
    path("register/", views.register_user, name="register"),
    path("logout/", views.logout_user, name="logout"),
    path("update_user/", views.update_user, name="update_user"),
    path("task_creation/", views.task_creation, name="task_creation"),
    path("task_completion/<int:id>/", views.task_completion, name="task_completion"),
    path("task_update/<int:id>/", views.task_update, name="task_update"),
    path("task_delete/<int:id>/", views.task_delete, name="task_delete"),
    path("user_profile/", views.user_profile, name='user_profile'),
    path("task_completed/<int:id>/", views.task_completed, name='task_completed')



]

task_lad/templates/footer.html
<footer class="dark-section  text-center d-flex flex-column align-items-center justify-content-center">
    <i class="bi bi-globe2  footer-icon"></i>
    <p class="footer-text text-center">Contact me and get in touch!
    </p>
    <div class="social-networks-icons d-flex flex-wrap align-items-center justify-content-center" >

      <a href="https://github.com/YeyoDev99" target="_blank" rel="noopener noreferrer">
        <i class="bi bi-github"></i>

      </a>
      <a href="mailto:yeyoduglas2004@gmail.com" target="_blank" rel="noopener noreferrer">
        <i class="bi bi-envelope"></i>

      </a>
    </div>
    <div class="copyright">
      created by yeyoDev99 (2023) &#169;
    </div>  
  </footer>

task_lad/templates/main.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="robots" content="index, follow"/> 
    <title>task_lad</title>
    <meta name="description" content="Task Lad is the lad you need to take the lead of your life"/> 
    <link rel="stylesheet" href=" {% static 'basic.css' %} ">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=PT+Sans+Narrow&display=swap" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Titillium+Web:wght@600&display=swap" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Alkatra&display=swap" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
</head>
<body>
    <header class='sticky-top'>
        {% include 'navbar.html' %}
    </header>
    
    <main>
        {% block content %}
    
        {% endblock content %}
        
    </main>
    
    <footer>
        {% include 'footer.html' %}
    </footer>
    

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>

</body>
</html>

task_lad/templates/navbar.html
<nav class="navbar navbar-expand-md navbar-light ">
    <div class="container-fluid">
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbar-toggler" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbar-toggler">
        <a class="navbar-brand" href="{% url 'task_page:index' %}"><h1 id="title">Task Lad</h1></a>
        <ul class="navbar-nav d-flex justify-content-center align-items-center">
                  <li class="nav-item home">
                    <a class="nav-link" aria-current="page" href="{% url 'task_page:index' %}">home</a>
                </li>
            {% if request.user.is_authenticated %}  
                <li class="nav-item">
                    <a class="nav-link" aria-current="page" href="{% url 'task_page:user_profile' %}">your profile</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href=" {% url 'task_page:logout' %} ">logout</a>
                </li>
          {% endif %}
        </ul>
      </div>
    </div>
  </nav>