task_lad/task_lad/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('task_page.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

task_lad/task_page/urls.py
from django.urls import path
from . import views

app_name = 'task_page'

urlpatterns = [
    path("", views.index, name='index'),
    path("login/", views.login_user, name="login"),
    path("register/", views.register_user, name="register"),
    path("logout/", views.logout_user, name="logout"),
    path("update_user/", views.update_user, name="update_user"),
    path("task_creation/", views.task_creation, name="task_creation"),
    path("task_completion/<int:id>/", views.task_completion, name="task_completion"),
    path("task_update/<int:id>/", views.task_update, name="task_update"),
    path("task_delete/<int:id>/", views.task_delete, name="task_delete"),
    path("user_profile/", views.user_profile, name='user_profile'),
    path("task_completed/<int:id>/", views.task_completed, name='task_completed')



]

task_lad/task_page/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
import datetime
from django.contrib import admin
from django.utils import timezone


class User(AbstractUser):
    name = models.CharField(max_length=200, null=True, blank=True)
    avatar = models.ImageField(default='default.jpg', null=True, blank=True)
    bio = models.TextField(null=True, blank=True)

    def __str__(self):
        return self.username

class Task(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField(null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    deadline = models.DateTimeField(default=timezone.now())
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=1)
    completion = models.BooleanField(default=False)
    delay = models.BooleanField(default=False)
    completed = models.DateTimeField(null=True, blank=True)

    @admin.display(boolean=True, ordering="completion", description="completed?")
    def completion_validation(self):
        return self.completion
    

    @admin.display(boolean=True, ordering="deadline", description="delayed completion?")
    def delay_validation(self):
        return self.delay


    def __str__(self):
        return self.title

task_lad/task_page/forms.py
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from .models import User, Task
from django.contrib.admin.widgets import AdminSplitDateTime 
from django import forms

help_text_password = '''

Your password can’t be too similar to your other personal information. 
Your password must contain at least 8 characters. 
Your password can’t be a commonly used password. 
Your password can’t be entirely numeric.

Password


'''


class UserRegisterForm(UserCreationForm):
    
    password1 = forms.CharField(
        label= "Password",
        widget=forms.PasswordInput(attrs={'class':'form-control', 'type':'password','placeholder':'password', 'id': 'password'}),
    )
    password2 = forms.CharField(
        label="Confirm password",
        widget=forms.PasswordInput(attrs={'class':'form-control', 'type':'password', 'placeholder':'password'}),
    )

    class Meta:
        model = User
        fields = ['name', 'email','username','avatar','password1', 'password2']
        widgets= {
            'name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'write your name'}),
            'email': forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'write your email'}),
            'username': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'write your username'}),
            'avatar': forms.FileInput(attrs={'class': 'form-control'}),

        }

class UserUpdateForm(ModelForm):
    class Meta:
        model = User
        fields = ['avatar', 'name', 'bio']
        widgets= {
            'avatar': forms.FileInput(attrs={'class': 'form-control'}),
            'name': forms.TextInput(attrs={'class': 'form-control dick', 'placeholder': 'write your name'}),
            'bio': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'write about you'}),

        }   


class TaskCreationForm(ModelForm):
    class Meta:
        model = Task
        fields = '__all__'
        exclude = ['created', 'updated', 'user', 'completion', 'delay', 'completed'] 
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'write the task title'}),
            
            'description': forms.Textarea(attrs={
                                                'class': 'form-control description-text',
                                                'placeholder': 'task description'   
                                                }),
            
            'deadline': forms.DateTimeInput(attrs={
                                            'class': 'form-control', 
                                            'type': "datetime-local"}),

        }

class TaskUpdateForm(ModelForm):
    class Meta:
        model = Task
        fields = '__all__'
        exclude = ['created', 'updated', 'user', 'delay', 'completed', 'completion'] 
        widgets= {
            'title': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'write the task title'}),
            
            'description': forms.Textarea(attrs={
                                                'class': 'form-control description-text',
                                                'placeholder': 'task description'   
                                                }),
            
            'deadline': forms.DateTimeInput(attrs={
                                            'class': 'form-control', 
                                            'type': "datetime-local"}),

        }   

task_lad/task_page/views.py
from django.contrib.auth import login, logout, authenticate
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from .models import User, Task
import datetime
from .forms import UserRegisterForm, UserUpdateForm, TaskCreationForm, TaskUpdateForm
from django.contrib import messages
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.utils import timezone


# task modifications
def index(request):
    if request.user.is_authenticated:
        user = User.objects.get(pk = request.user.id )
        tasks = user.task_set.filter(Q(completion = False)).order_by('deadline')[:5]
        tasks_number = tasks.count()

        context = {
            'tasks': tasks,
            'tasks_number': tasks_number
        }
        return render(request, 'task_page/index.html', context)
    else: 
        context = {}
        return render(request, 'task_page/index.html', context)
    

def login_user(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        try:
            user = User.objects.get(username = username)
        except:
            messages = ["the user does not exist"]
            context = {
                'messages': messages
            }
            return render(request, 'task_page/index.html', context)

        else:
            user = authenticate(request, username= username, password=password) 
            if user is not None:
                login(request, user)
                return HttpResponseRedirect(reverse('task_page:index'))
            else:
                messages = ["username or password incorrect"]
                context = {
                'messages': messages
                }
                return render(request, 'task_page/index.html', context)
    context = {}
    return render(request, 'task_page/login_user.html', context)


@login_required(login_url='task_page:index')
def logout_user(request):
    logout(request)
    return redirect('task_page:index')


def register_user(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST, request.FILES)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('task_page:index')
        else:
            messages.error(request, 'something went wrong on the registration, try again')
    form = UserRegisterForm()
    context = {
        'form': form
        }
    return render(request, 'task_page/register_user.html', context)
    

@login_required(login_url='task_page:index')
def update_user(request):
    if request.method == 'POST':
            form = UserUpdateForm(request.POST, request.FILES, instance=request.user)
            if form.is_valid():
                form.save()
                return redirect('task_page:index')
            else:
                messages.error(request, "something went wrong on the user update")
    form =  UserUpdateForm(instance=request.user)
    context = {
        'form': form
    }   
    return render(request, 'task_page/update_user.html', context)


@login_required(login_url='task_page:index')
def task_creation(request):
    if request.method == 'POST':
        form = TaskCreationForm(request.POST)
        if form.is_valid():
            task = form.save(commit=False)
            task.user = request.user
            if task.deadline >= timezone.now():  
                task.save()
                return redirect('task_page:index')
            else:
                messages.error(request, 'please set a greater deadline than the current datetime')
        else:
            messages.error(request, 'something went wrong during the task creation')
    form = TaskCreationForm()
    context = {
        'form': form
    }
    return render(request, 'task_page/task_creation.html', context)


@login_required(login_url='task_page:index')
def task_completion(request, id):
    task = get_object_or_404(Task, pk=id)
    task.completion = True
    task.completed = timezone.now()
    if task.completed > task.deadline:
        task.delay = True
    else:
        task.delay = False    
    task.save()
    return redirect("task_page:index")


@login_required(login_url='task_page:index')
def task_update(request, id):
    task = get_object_or_404(Task, pk=id)
    q = request.GET.get('q')
    if q == None:
        if request.method == 'POST':
            form = TaskUpdateForm(request.POST,instance=task)
            if form.is_valid():
                task = form.save(commit=False)
                if task.deadline >= timezone.now():  
                    task.save()
                    return redirect('task_page:index')
                else:
                    messages.error(request, 'please set a greater deadline than the current datetime')
            else:
                messages.error(request, 'something went wrong during task update')
        form = TaskUpdateForm(instance=task)
    else:
        task.deadline = timezone.now()
        task.completion = False
        task.delay = False
        task.save()
        form = TaskUpdateForm(instance=task)  
    context = {
        'form': form,
        'id': id
    }
    return render(request, 'task_page/task_update.html', context)


@login_required(login_url='task_page:index')
def task_delete(request, id):
    task = get_object_or_404(Task, pk=id)
    task.delete()
    return redirect('task_page:index')


@login_required(login_url='task_page:index')
def user_profile(request):
    user = request.user
    q = request.GET.get('q') if request.GET.get('q') != None else 'tasks'
    filters = {
        'tasks': user.task_set.all(),
        'completed tasks': user.task_set.filter(completion = True),
        'uncompleted tasks': user.task_set.filter(completion = False),
        'delayed tasks': user.task_set.filter(delay = True),
        'in time tasks': user.task_set.filter(delay = False),
        'uncompleted delayed tasks': user.task_set.filter(Q(delay = True) & Q(completion=False)),
        'completed delayed tasks': user.task_set.filter(Q(delay = True) & Q(completion=True)),
        'completed in time tasks': user.task_set.filter(Q(delay = False) & Q(completion=True)),
        'uncompleted in time tasks': user.task_set.filter(Q(delay = False) & Q(completion=False)),    
    }
    tasks = filters[q]
    tasks_count = tasks.count()
    context = {
        'filters': filters,
        'tasks': tasks,
        'tasks_count': tasks_count,
        'q': q
                }
    return render(request, 'task_page/user_profile.html', context)    


@login_required(login_url='task_page:index')
def task_completed(request, id):
    task = get_object_or_404(Task, pk=id)
    context = {
        'task': task
        }
    return render(request, 'task_page/task_completed.html', context)

task_lad/task_page/templates/task_page/index.html
{% extends "main.html" %}

{% block content %}
<div class='index  d-flex flex-column justify-content-center  align-items-center'>
    {% if request.user.is_authenticated %}
        <p>welcome back <span>@{{request.user}}</span>,  lets have a productive day!</p>
        <p>you have {{tasks_number}} upcoming task{{ tasks_number|pluralize }} to complete: </p>
        <p style='text-align: center;'><strong><a href=" {% url 'task_page:task_creation' %} "> create a task</a></strong></p>
        {% for task in tasks %}
        <div class='task-feed-container index-feed'>
            <h5><a href=" {% url 'task_page:task_update' task.id %}  "> {{ task.title }} </a></h5>
            <small> {{task.description}} </small>
            <p><a href=" {% url 'task_page:task_completion' task.id %} "> mark as completed </a> | 
                <a href=" {% url 'task_page:task_delete' task.id %} ">delete task</a></p>
        </div>
        <br>
        {% endfor %}
        
    {% else %}
        {% include "task_page/login_user.html" %}
        
    {% endif %}
</div>
    
{% endblock content %}

task_lad/task_page/templates/task_page/login_user.html
    
    <form  class='login d-flex flex-column justify-content-center align-items-center' action="{% url 'task_page:login' %}" method='POST'>
        {% if messages %}
        {% for message in messages %}
            <p><strong> {{ message }} </strong></p>
        {% endfor %}
    {% endif %}
        {% csrf_token %}
        <br>
        <div class="input-group ">
            <span class="input-group-text" id="basic-addon1"><i class="login-icon bi bi-person"></i></span>
            <input aria-describedby="basic-addon1" class='login-input form-control' type="text" placeholder="username" name="username" >    
        </div>
        <br>
        <div class="input-group">
            <span class="input-group-text" id="basic-addon1"><i class="login-icon bi bi-key"></i></i></span>
            <input aria-describedby="basic-addon1" class='login-input form-control' type="password" placeholder="password" name='password'>    
        </div>
        <br>
        <button type='submit'>login</button>
        <p style='text-align: center;'>haven't signed up yet? <a href=" {% url 'task_page:register' %} "><br><strong>click here</strong></a></p>
    </form>

task_lad/task_page/templates/task_page/register_user.html
{% extends "main.html" %}

{% block content %}
    <div class="d-flex flex-column justify-content-center align-items-center" >
        <div class='user-registration d-flex flex-column justify-content-center align-items-center text-center'> 
            {% if messages %}
                {% for message in messages %}
                    <p><strong> {{ message }} </strong></p>
                {% endfor %}
            {% endif %}
        <form class="d-flex flex-column justify-content-center align-items-center text-center" action="" method='POST' enctype='multipart/form-data' >
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">
                register
            </button>
            <p><strong><a href=" {% url 'task_page:index' %} ">return to the previous page</a></strong></p>
        </form>
    
        </div>
    
    </div>

{% endblock content %}

task_lad/task_page/templates/task_page/task_completed.html
{% extends "main.html" %}

{% block content %}
    <div class="d-flex flex-column  text-center justify-content-center align-items-center" >
        <div class="completed-task d-flex flex-column  text-center justify-content-center align-items-center" >
            <h2>{{task.title}}</h2>
            <p>{{task.description}}</p>
            {% if delay %}
            <p><strong>delayed</strong></p>
            {% else %}
        
            <p><strong>completed in time</strong></p>
            {% endif %}
            <p class='datetime'>created at {{task.created}}</p>
            <p class='datetime'>deadline at {{task.deadline}}</p>
            <button><a href=" {% url 'task_page:task_update' task.id %}?q='task_restore' ">restore task</a></button>
            <p><strong><a href=" {{ request.META.HTTP_REFERER }} ">return to the previous page</a></strong></p>
        
        </div>
    
    </div>
{% endblock content %}

task_lad/task_page/templates/task_page/task_creation.html
{% extends "main.html" %}


{% block content %}
<div class="d-flex flex-column justify-content-center align-items-center">
    <div class="task-creation  d-flex text-center flex-column justify-content-center align-items-center">
        {% if messages %}
            {% for message in messages %}
                <p><strong> {{ message }} </strong></p>
            {% endfor %}
        {% endif %}
        <form class="task-creation-form d-flex flex-column justify-content-center align-items-center" action="" method='POST'>
            {% csrf_token %}
            {{ form.as_p }}
            <button type='submit'>create</button>
            <p><strong><a href=" {{ request.META.HTTP_REFERER }} ">return to the previous page</a></strong></p>
        </form>
        
    </div>
</div>


{% endblock content %}

task_lad/task_page/templates/task_page/task_feed.html
<div class='task-feed-list d-flex flex-column justify-content-center align-items-center'>
    <h3>Tasks:</h3>
    <p>you have {{tasks_count}} {{q}} </p>
    {% for task in tasks %}
    <div class='task-feed-container d-flex flex-column justify-content-center align-items-center'>
        {% if task.completion %}
            <h3><a href=" {% url 'task_page:task_completed' task.id %}  "> {{ task.title }} </a></h5>
        
        {% else %}
            <h3><a href=" {% url 'task_page:task_update' task.id %}  "> {{ task.title }} </a></h3>

        {% endif %}
            <p> {{task.description}} </p>  
            <p>
            {% if not task.completion %}    
                <a href=" {% url 'task_page:task_completion' task.id %} ">mark as completed</a> | 
            {% endif %} 
                <a href=" {% url 'task_page:task_delete' task.id %} ">delete task</a>        
            </p>   
            <!--  the next thing to do is the CRUD for the tasks -->
        
        
    </div>
    <br>
    {% endfor %}
        
</div>

task_lad/task_page/templates/task_page/task_filter.html
<ul class='task_feed'>
    <h3>Search by:</h3>

    {% for filter in filters.keys %}
    <li><a href=" {% url 'task_page:user_profile' %}?q={{filter}}">{{filter}}</a></li>
    {% if forloop.counter == 1 or forloop.counter == 5 %}
        <hr>
    {% endif %}
    {% endfor %}
</ul>

task_lad/task_page/templates/task_page/task_update.html
{% extends "main.html" %}

{% block content %}
<div class='d-flex flex-column justify-content-center align-items-center text-center'>
    <div class="task-update d-flex flex-column justify-content-center align-items-center ">
        {% if messages %}
        {% for message in messages %}
            <p><strong> {{ message }} </strong></p>
        {% endfor %}
        {% endif %}
        <form class=' d-flex flex-column justify-content-center align-items-center' action=" {% url 'task_page:task_update' id %} " method='POST'>
        {% csrf_token %}
        {{ form.as_p }}
        <button type='submit'>update</button>
        <p><strong><a href=" {{ request.META.HTTP_REFERER }} ">return to the previous page</a></strong></p>
        </form>
    </div>
</div>


{% endblock content %}

task_lad/task_page/templates/task_page/update_user.html
{% extends "main.html" %}

{% block content %}
<div class="d-flex flex-column justify-content-center align-items-center text-center">
    <div class="user-update d-flex flex-column justify-content-center align-items-center text-center">
        {% if messages %}
            {% for message in messages %}
                <p><strong> {{ message }} </strong></p>
            {% endfor %}
        {% endif %}
        <form class="d-flex flex-column justify-content-center align-items-center text-center" action="" method='POST' enctype='multipart/form-data'>
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">update</button>
            <p><strong><a href=" {{ request.META.HTTP_REFERER }} ">return to the previous page</a></strong></p>
        </form>

    </div>
</div>

{% endblock content %}

task_lad/task_page/templates/task_page/user_profile.html
{% extends "main.html" %}

{% block content %}
    
    
    <div class='profile_c container-fluid'>
        <div class='row'>
            <div class='task-filter col-12 col-md-6'>
                {% include "task_page/task_filter.html" %}
            
            </div>
        
            <div class='user-and-tasks col-12 col-md-6 d-flex flex-column justify-content-center align-content-center'>
                <div class="div d-flex flex-column justify-content-center align-content-center">
                    <div class='user-container'>
                        <p class="user-id">{{ request.user.name }} | <small>@{{request.user}}</small></p>
                        <p><a href=" {% url 'task_page:update_user' %} "><img class='profile-image-big' src=" {{request.user.avatar.url}} " alt="user avatar"/></a></p>
                        {% if request.user.bio is not None %}         
                            <p>{{ request.user.bio }}</p>            
                        {% endif %}
                    </div>
                    <hr>
                    
        
                    {% include "task_page/task_feed.html" %}
                </div>

            
            </div>
            
        </div>
        
        
    </div>
    


{% endblock content %}